#!/bin/sh
#
# Perform necessary setup steps
# after package is installed.
#

PROGNAME=`basename $0`
INSTALLER_DIR=/opt/chef-workstation

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

is_darwin()
{
  uname -v | grep "^Darwin" 2>&1 >/dev/null
}

if is_darwin; then
    PREFIX="/usr/local"
    mkdir -p "$PREFIX/bin"
else
    PREFIX="/usr"
fi

# TODO - pull from components/*/bin/*?
# We test for the presence of /usr/bin/chef-client to know if this script succeeds,
# so chef-client must appear as the last item here.
chefdk_binaries="berks chef chef-apply chef-shell chef-solo chef-vault cookstyle dco delivery foodcritic inspec kitchen knife ohai push-apply pushy-client pushy-service-manager chef-client"
binaries="chef-run chefx $chefdk_binaries"

for binary in $binaries; do
  ln -sf $INSTALLER_DIR/bin/$binary $PREFIX/bin || error_exit "Cannot link $binary to $PREFIX/bin"
done

if is_darwin; then
  echo "TODO: mac CWA setup is not implemented"
else
  cwa_path ="$INSTALLER_DIR/components/chef-workstation-app/chef-workstation-app"

  # TODO - is ldd available by default on target linux systems?
  # 0 rc means grep found 'not found' text - and we have missing deps.
  ldd $cwa_path | grep "not found" > /dev/null  2>&1
  if [ $? -eq 0 ]; then
    echo "This system is missing dependencies required for the desktop Chef Workstation App. It will not be available on this node."
  else
    ln -sf $app_path $PREFIX/bin
  fi
fi


echo "Thank you for installing Chef Workstation!"
echo "You can find some tips on getting started at https://chef.sh/"

exit 0
